# yml to  Step 4- Add Deployment to GitHub Actions (optional CI/CD)
name: My Flask App CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: |
        pytest
# Seguido verificamos si pasó el test se dispara el webhook para avisrle a render que deploye nomás        
    - name: Deploy to Render
      if: success()
      run: |
        curl -X "${{ secrets.RENDER_DEPLOY_HOOK }}"
